import uPlot from "uplot";
import "uplot/dist/uPlot.min.css";
import "./app.css";
import "./extra.css";

type Target={id:string,name:string,address:string,endpoint?:string,state:string,last_rtt_ms?:number};
type Point={time_ms:number,scheduled:number,attempted:number,sent:number,late:number,unanswered:number,send_errors:number,scheduler_missed:number,min_ms?:number,p50_ms?:number,p95_ms?:number,p99_ms?:number,max_ms?:number,timeout_max_ms?:number,deadline_miss_pct:number,no_reply_pct:number,late_pct?:number,send_error_pct?:number,gap_pct?:number};
const $=(s:string)=>document.querySelector(s) as HTMLElement;
let target:string|null=null,selectedInterface:string|null=null,range=6*3600e3,targets:Target[]=[];
let latency:uPlot|null=null,loss:uPlot|null=null,interfacePlot:uPlot|null=null;
let viewport:{from:number,to:number}|null=null,seriesRequest=0,traceRequest=0;
const ranges:Record<string,number>={"1h":3600e3,"6h":6*3600e3,"24h":86400e3,"7d":7*86400e3,"30d":30*86400e3};
async function api(path:string){const r=await fetch(path,{headers:{accept:"application/json"}});if(!r.ok)throw new Error(await r.text());return r.json()}
function esc(s:string){const e=document.createElement("span");e.textContent=s;return e.innerHTML}
function rangeButtons(){const el=$("#ranges");el.innerHTML="";for(const[n,v]of Object.entries(ranges)){const b=document.createElement("button");b.textContent=n;b.className=v===range&&!viewport?"active":"";b.onclick=()=>{range=v;viewport=null;rangeButtons();loadSeries()};el.append(b)}}
function renderTargets(){const el=$("#targets");el.innerHTML=targets.map(t=>`<button class="target ${t.id===target?"active":""}" data-id="${esc(t.id)}"><i class="dot ${t.state}"></i><span><strong>${esc(t.name)}</strong><small>${esc(t.endpoint||t.address)}</small></span><span class="rtt">${t.last_rtt_ms==null?"—":t.last_rtt_ms.toFixed(1)+" ms"}</span></button>`).join("");el.querySelectorAll<HTMLButtonElement>("button").forEach(b=>b.onclick=()=>select(b.dataset.id!))}
function select(id:string){target=id;viewport=null;renderTargets();rangeButtons();const t=targets.find(x=>x.id===id)!;$("#title").textContent=t.name;$("#subtitle").textContent=t.endpoint||t.address;loadSeries();loadTraces()}
function graph(el:string,old:uPlot|null,points:any[],fields:string[],labels:string[],colors:string[],max?:number,zoom?:(from:number,to:number)=>void){old?.destroy();const data:any[]=[points.map(p=>p.time_ms/1000),...fields.map(f=>points.map(p=>p[f]??null))];const root=$(el);return new uPlot({width:Math.max(280,root.clientWidth),height:215,legend:{show:true},cursor:{drag:{x:true,y:false}},scales:{y:{range:max?()=>[0,max]:undefined}},axes:[{stroke:"#82949f",grid:{stroke:"#20313a"}},{stroke:"#82949f",grid:{stroke:"#20313a"}}],series:[{},...labels.map((label,i)=>({label,stroke:colors[i],width:1.6}))],hooks:{setSelect:[u=>{if(!zoom||u.select.width<8)return;const from=u.posToVal(u.select.left,"x")*1000,to=u.posToVal(u.select.left+u.select.width,"x")*1000;queueMicrotask(()=>zoom(from,to))}]}},data,root)}
async function loadSeries(fromArg?:number,toArg?:number){if(!target)return;if(fromArg!=null&&toArg!=null){viewport={from:fromArg,to:toArg};rangeButtons()}const bounds=viewport??{to:Date.now(),from:Date.now()-range},to=bounds.to,from=bounds.from,id=++seriesRequest,selected=target;try{const s=await api(`/api/v1/targets/${encodeURIComponent(selected)}/ping?from=${Math.round(from)}&to=${Math.round(to)}&max_points=900`);if(id!==seriesRequest||selected!==target)return;const p:Point[]=s.points??[];p.forEach(x=>{x.late_pct=x.sent?100*x.late/x.sent:0;x.send_error_pct=x.attempted?100*x.send_errors/x.attempted:0;x.gap_pct=x.scheduled?100*x.scheduler_missed/x.scheduled:0});latency=graph("#latency",latency,p,["min_ms","p50_ms","p95_ms","p99_ms","max_ms","timeout_max_ms"],["min","p50","p95","p99","max","timeout"],["#477780","#5bd6d0","#f0a657","#ef6b66","#8c5b71","#c0c9ce"],undefined,(a,b)=>loadSeries(a,b));loss=graph("#loss",loss,p,["deadline_miss_pct","no_reply_pct","late_pct","send_error_pct","gap_pct"],["deadline miss","no reply","late reply","local send error","scheduler gap"],["#ef6b66","#f0a657","#d45d9e","#b18cff","#82949f"],100);const last=p.at(-1)||{} as Point,sent=p.reduce((a,x)=>a+x.sent,0),miss=p.reduce((a,x)=>a+x.late+x.unanswered,0),no=p.reduce((a,x)=>a+x.unanswered,0);$("#stats").innerHTML=stat("Latest p50",last.p50_ms==null?"—":last.p50_ms.toFixed(2)+" ms")+stat("Deadline miss",sent?(100*miss/sent).toFixed(2)+"%":"—")+stat("No reply",sent?(100*no/sent).toFixed(2)+"%":"—")+stat("Packets sent",sent.toLocaleString())}catch(e){if(id===seriesRequest)$("#subtitle").textContent=(e as Error).message}}
function stat(k:string,v:string){return`<div class="stat"><label>${k}</label><strong>${v}</strong></div>`}
async function loadInterface(name:string){selectedInterface=name;const bounds=viewport??{to:Date.now(),from:Date.now()-range};const series=await api(`/api/v1/interfaces/${encodeURIComponent(name)}/series?from=${bounds.from}&to=${bounds.to}&max_points=500`);const points:any[]=series.points??[];points.forEach((p:any)=>p.reset_marker=p.reset?1:null);$("#interface-title").textContent=name;interfacePlot=graph("#interface-chart",interfacePlot,points,["rx_mbps","tx_mbps","rx_errors","tx_errors","rx_dropped","tx_dropped","rx_missed","reset_marker"],["RX Mbps","TX Mbps","RX errors","TX errors","RX dropped","TX dropped","RX missed","RESET"],["#5bd6d0","#f0a657","#ef6b66","#b18cff","#6e9cc9","#c77d65","#82949f","#ff3158"])}
function routeDiff(r:any){const old=new Map<number,string>((r.old_route??[]).map((h:any)=>[h.ttl,(h.responders??[]).join(", ")]));const next=new Map<number,string>((r.new_route??[]).map((h:any)=>[h.ttl,(h.responders??[]).join(", ")]));const changed=[...new Set([...old.keys(),...next.keys()])].sort((a,b)=>a-b).filter(ttl=>old.get(ttl)!==next.get(ttl));const hops=changed.map(ttl=>`${ttl}: ${old.get(ttl)||"*"} → ${next.get(ttl)||"*"}`).join("; ");const reached=r.old_reached_hop!==r.new_reached_hop?`reached ${r.old_reached_hop||"no"} → ${r.new_reached_hop||"no"}`:"";return [hops,reached].filter(Boolean).join(" · ")||"hop set changed"}
async function loadTraces(){if(!target)return;const id=++traceRequest,selected=target;const[rawTraces,rawChanges]=await Promise.all([api(`/api/v1/targets/${encodeURIComponent(selected)}/traces?limit=12`),api(`/api/v1/route-changes?target=${encodeURIComponent(selected)}&limit=6`)]);if(id!==traceRequest||selected!==target)return;const traces:any[]=rawTraces??[],changes:any[]=rawChanges??[];const el=$("#routes");const changed=changes.map((r:any)=>`<div class="row"><strong>Route changed</strong><span>${new Date(r.confirmed_ms).toLocaleString()} · ${esc(routeDiff(r))}</span></div>`).join("");const runs=traces.map((r:any)=>`<button class="row trace-row" data-id="${r.id}"><strong>${new Date(r.started_ms).toLocaleString()}</strong><span>${esc(r.method)} · ${r.reached?"reached hop "+r.reached_hop:esc(r.error_detail||r.status)}</span></button>`).join("");el.innerHTML=changed+runs||"<div class=empty>No trace runs yet</div>";el.querySelectorAll<HTMLButtonElement>("button").forEach(b=>b.onclick=()=>loadTrace(Number(b.dataset.id)))}
async function loadTrace(id:number){const trace=await api(`/api/v1/traces/${id}`);const hops=new Map<number,string[]>();for(const p of trace.probes??[]){const values=hops.get(p.ttl)||[];values.push(p.responder?`${p.responder}${p.rtt_ms==null?"":` (${p.rtt_ms.toFixed(1)} ms)`}`:"*");hops.set(p.ttl,values)}$("#trace-detail").innerHTML=[...hops].map(([ttl,v])=>`<div class="row"><strong>${ttl}</strong><span>${v.map(esc).join(" · ")}</span></div>`).join("")||`<div class=empty>${esc(trace.error_detail||"No probe replies")}</div>`}
async function refresh(){try{targets=(await api("/api/v1/targets"))??[];renderTargets();if(!target&&targets.length)select(targets[0].id);else if(target){loadSeries();loadTraces()}const ifs:any[]=(await api("/api/v1/interfaces"))??[];const interfaces=$("#interfaces");interfaces.innerHTML=ifs.length?ifs.map((i:any)=>`<button class="row trace-row" data-name="${esc(i.name)}"><strong>${esc(i.display_name)}</strong><span>${i.present?esc(i.mac||"observed"):"missing"}</span></button>`).join(""):"<div class=empty>No interfaces configured</div>";interfaces.querySelectorAll<HTMLButtonElement>("button").forEach(b=>b.onclick=()=>loadInterface(b.dataset.name!));if(selectedInterface)loadInterface(selectedInterface);const status=await api("/api/v1/status");const traceState=Object.entries(status.trace_capabilities??{}).filter(([,v])=>v!=="available"&&v!=="disabled").map(([k,v])=>`${k} ${v}`);if(status.interface_capability?.startsWith("unavailable"))traceState.push(`interfaces ${status.interface_capability}`);$("#storage").textContent=`Storage ${status.pressure} · ${formatBytes(status.live_bytes)} live · ${status.dirty_buckets} dirty buckets${traceState.length?" · "+traceState.join(" · "):""}`;$("#health").textContent=status.ready?"ready":"paused";$("#health").className=status.ready?"pill ready":"pill";$("#health").title=status.writer_error||`${formatBytes(status.available_bytes)} filesystem space available`}catch{$("#health").textContent="unavailable";$("#health").className="pill"}}
function formatBytes(n:number){for(const[u,v]of[["TiB",2**40],["GiB",2**30],["MiB",2**20]] as [string,number][]){if(n>=v)return(n/v).toFixed(1)+" "+u}return n+" B"}
rangeButtons();refresh();setInterval(refresh,5000);addEventListener("resize",()=>loadSeries());
